repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/oss
   - https://stocksoftware.jfrog.io/stocksoftware/staging
   - https://stocksoftware.jfrog.io/stocksoftware/thirdparty-local

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  braincheck: org.realityforge.braincheck:braincheck:jar:1.25.0

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:2.25
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:2.25
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:2.25

  arez_core: org.realityforge.arez:arez-core:jar:0.146
  arez_processor: org.realityforge.arez:arez-processor:jar:0.146
