repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.9

  javax_jsr305: com.google.code.findbugs:jsr305:jar:3.0.1
  jetbrains_annotations: org.jetbrains:annotations:jar:15.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.92

  autoservice: com.google.auto.service:auto-service:jar:1.0-rc3
  autocommon: com.google.auto:auto-common:jar:0.8
  javapoet: com.squareup:javapoet:jar:1.7.0
  guava: com.google.guava:guava:jar:21.0

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.11
  truth: com.google.truth:truth:jar:0.35
