repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/staging
   - http://repo1.maven.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/oss
   - https://stocksoftware.jfrog.io/stocksoftware/thirdparty-local

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.13

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.0.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.96

  autoservice: com.google.auto.service:auto-service:jar:1.0-rc3
  autocommon: com.google.auto:auto-common:jar:0.10
  javapoet: com.squareup:javapoet:jar:1.11.1
  guava: com.google.guava:guava:jar:25.0-jre

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.15
  truth: com.google.truth:truth:jar:0.39
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-RC1

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:1.0.0-b15-7a28038
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:1.0.0-b15-7a28038
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:1.0.0-b15-7a28038

  braincheck: org.realityforge.braincheck:braincheck:jar:1.12.0

  javax_json: org.glassfish:javax.json:jar:1.1

  jsonassert: org.skyscreamer:jsonassert:jar:1.5.0
  android_json: com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1

  javax_inject: javax.inject:javax.inject:jar:1
  dagger_core: com.google.dagger:dagger:jar:2.19
  dagger_producers: com.google.dagger:dagger-producers:jar:2.19
  dagger_spi: com.google.dagger:dagger-spi:jar:2.19
  dagger_compiler: com.google.dagger:dagger-compiler:jar:2.19
  googlejavaformat: com.google.googlejavaformat:google-java-format:jar:1.5
  errorprone: com.google.errorprone:javac-shaded:jar:9-dev-r4023-3

  gin: com.google.gwt.inject:gin:jar:2.1.2
  aopalliance: aopalliance:aopalliance:jar:1.0
  guice: com.google.inject:guice:jar:3.0
  guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0

  gir: org.realityforge.gir:gir-core:jar:0.07

  javacsv: net.sourceforge.javacsv:javacsv:jar:2.1

  gwt_symbolmap: org.realityforge.gwt.symbolmap:gwt-symbolmap:jar:0.08

  testng: org.testng:testng:jar:6.11

  jdepend: guru.nidi:jdepend:jar:2.9.5

  revapi_diff: org.realityforge.revapi.diff:revapi-diff:jar:all:0.03
