repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  braincheck: org.realityforge.braincheck:braincheck:jar:1.29.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.05

  akasha: org.realityforge.akasha:akasha-java:jar:0.03

  arez_core: org.realityforge.arez:arez-core:jar:0.193
  arez_processor: org.realityforge.arez:arez-processor:jar:0.193
