repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.10

  javax_jsr305: com.google.code.findbugs:jsr305:jar:3.0.1
  jetbrains_annotations: org.jetbrains:annotations:jar:15.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.92

  autoservice: com.google.auto.service:auto-service:jar:1.0-rc3
  autocommon: com.google.auto:auto-common:jar:0.8
  javapoet: com.squareup:javapoet:jar:1.7.0
  guava: com.google.guava:guava:jar:21.0

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.11
  truth: com.google.truth:truth:jar:0.35

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.1

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.1
  jsinterop_annotations_sources: com.google.jsinterop:jsinterop-annotations:jar:sources:1.0.1

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-beta-1
  jsinterop_base_sources: com.google.jsinterop:base:jar:sources:1.0.0-beta-1

  elemental2_core: com.google.elemental2:elemental2-core:jar:1.0.0-beta-1
  elemental2_dom: com.google.elemental2:elemental2-dom:jar:1.0.0-beta-1
  elemental2_promise: com.google.elemental2:elemental2-promise:jar:1.0.0-beta-1

  braincheck: org.realityforge.braincheck:braincheck:jar:gwt:1.1.0

  javax_json: org.glassfish:javax.json:jar:1.1

  jsonassert: org.skyscreamer:jsonassert:jar:1.5.0
  android_json: com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1
