repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/oss
   - https://stocksoftware.jfrog.io/stocksoftware/staging
   - https://stocksoftware.jfrog.io/stocksoftware/thirdparty-local

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.12

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.92

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  jetbrains_annotations: org.jetbrains:annotations:jar:15.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-RC1

  elemental2_core: com.google.elemental2:elemental2-core:jar:1.0.0-RC1
  elemental2_dom: com.google.elemental2:elemental2-dom:jar:1.0.0-RC1
  elemental2_promise: com.google.elemental2:elemental2-promise:jar:1.0.0-RC1

  arez_annotations: org.realityforge.arez:arez-annotations:jar:0.92
  arez_core: org.realityforge.arez:arez-core:jar:0.92
  arez_processor: org.realityforge.arez:arez-processor:jar:0.92
  arez_component: org.realityforge.arez:arez-component:jar:0.92

  braincheck: org.realityforge.braincheck:braincheck:jar:1.9.0

  testng: org.testng:testng:jar:6.11
