repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  braincheck: org.realityforge.braincheck:braincheck-core:jar:1.31.0

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  arez_core: org.realityforge.arez:arez-core:jar:0.197
  arez_processor: org.realityforge.arez:arez-processor:jar:0.197

  testng: org.testng:testng:jar:6.11
