repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/oss
   - https://stocksoftware.jfrog.io/stocksoftware/staging
   - https://stocksoftware.jfrog.io/stocksoftware/thirdparty-local

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  braincheck: org.realityforge.braincheck:braincheck:jar:1.20.0

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.102

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.0.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2

  jsinterop_base: org.realityforge.com.google.jsinterop:base:jar:1.0.0-b2-e6d791f

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:2.24
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:2.24
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:2.24

  arez_core: org.realityforge.arez:arez-core:jar:0.143
  arez_processor: org.realityforge.arez:arez-processor:jar:0.143

  testng: org.testng:testng:jar:6.11
