package arez;

import javax.annotation.Nonnull;

/**
 * Interface that used to intercept executions so that the environment can be setup when running.
 * Typically this is used to flag other runtimes to enable change batching etc.
 */
public interface Environment
{
  /**
   * Run the specified function.
   *
   * @param function the function.
   * @return the value generated by the function.
   */
  <T> T run( @Nonnull SafeFunction<T> function );

  /**
   * Run the specified function.
   *
   * @param function the function.
   * @return the value generated by the function.
   * @throws Throwable if the function throws an exception.
   */
  <T> T run( @Nonnull Function<T> function )
    throws Throwable;
}
