package arez;

import jsinterop.annotations.JsFunction;

/**
 * Functional interface for returning a value.
 *
 * @param <T> The type of the returned value.
 */
@FunctionalInterface
@JsFunction
public interface Function<T>
{
  /**
   * Return a value.
   *
   * @return the value generated by function.
   * @throws Throwable if unable to return value.
   */
  T call()
    throws Throwable;
}
