package arez;

/**
 * Functional interface for returning a value.
 *
 * @param <T> The type of the returned value.
 */
@FunctionalInterface
public interface SafeFunction<T>
{
  /**
   * Return a value.
   *
   * @return the value generated by function.
   */
  T call();
}
