title: Arez User Manual
url: "https://arez.github.io/"
baseurl: ""

permalink: pretty

keep_files: ["api", "examples"]

strict_front_matter: true

gems:
  - jekyll-sitemap
  - jekyll-toc

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

types:
  - minor
  - major
